DC-1496: Update v2 url
hmrc/customer-advisors-frontend pull request #14
Opened 2018-06-25 13:06 UTC by matthewgroom

2018-06-25 13:18 UTC, felixgb requested changes

2018-06-25 13:18 UTC, felixgb commented on conf/app1.routes
> +POST       /inbox/:utr             uk.gov.hmrc.contactadvisors.controllers.SecureMessageController.submit(utr: String)
Small thing but alignment here

2018-06-25 13:18 UTC, felixgb commented on conf/app1.routes
> +# microservice specific routes
Small thing but could there be a more descriptive routes file name(s) now? something like `cafe.routes` and `secure-message.routes`?

2018-06-25 13:33 UTC, felixgb commented on conf/prod.routes
> +->     	   /template                              template.Routes
Looks like a hard tab here

2018-06-26 10:40 UTC, felixgb approved these changes

2018-06-26 11:03 UTC, vasanthavijaya commented
Thanks Felix. Merging the request now.

2018-06-26 11:03 UTC, merged